# Generated by Django 3.1.7 on 2022-04-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='defi_talk_twi',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('Profile_Url', models.TextField()),
                ('Screen_Name', models.TextField()),
                ('User_Id', models.TextField()),
                ('Name', models.TextField()),
                ('Img_Url', models.TextField()),
                ('Background_Img', models.TextField()),
                ('Bio', models.TextField()),
                ('Website', models.TextField()),
                ('Location', models.TextField(default='')),
                ('Created_At', models.TextField()),
                ('Followers_Count', models.IntegerField()),
                ('Friends_Count', models.IntegerField()),
                ('Tweets_Count', models.IntegerField()),
                ('Certified', models.TextField()),
                ('Following', models.TextField()),
                ('Followed_By', models.TextField()),
                ('Query', models.TextField()),
                ('Timestamp1', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='defi_talk_twi_ads',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('User_Id', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
