# Generated by Django 3.1.7 on 2022-05-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_blockchain_lix_talk_ads_spaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='algorithm_fb_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
