# Generated by Django 3.1.7 on 2022-05-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_algorithm_fb_ads_spaced'),
    ]

    operations = [
        migrations.CreateModel(
            name='angle_investor_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='artificial_intelligence_fb_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='blockchain_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='business_angle_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='d3_design_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='data_analysis_fb_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='data_mining_fb_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='digital_marketing_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='enterpreneurs_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='graphic_design_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='machine_learning_fb_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='neural_network_fb_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='pitchdesk_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='private_investor_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='software_development_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='uiux_design_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='venture_capital_fb_talk_ads_spaced',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('uid', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
