# Generated by Django 3.1.7 on 2023-02-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_blogging_fb_ads_spaced_blogging_talk_content_marketing_fb_ads_spaced_content_marketing_talk_d3_anima'),
    ]

    operations = [
        migrations.CreateModel(
            name='figma_design_talk',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('Profile_URL', models.TextField()),
                ('Full_Name', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('Education', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='graphic_design_talk',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('Profile_URL', models.TextField()),
                ('Full_Name', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('Education', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='infographics_talk',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('Profile_URL', models.TextField()),
                ('Full_Name', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('Education', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='marketing_video_talk',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('Profile_URL', models.TextField()),
                ('Full_Name', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('Education', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='poadcasting_talk',
            fields=[
                ('Row_id', models.AutoField(primary_key=True, serialize=False)),
                ('Profile_URL', models.TextField()),
                ('Full_Name', models.TextField()),
                ('First_Name', models.TextField()),
                ('Last_Name', models.TextField()),
                ('Education', models.TextField()),
                ('Category', models.TextField()),
                ('contact', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
